# Generated by Django 5.2.9 on 2026-02-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="pokemon_images/"),
        ),
    ]
