# Generated by Django 5.2.9 on 2026-02-05 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0003_pokemonentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
