# Generated by Django 5.2.9 on 2026-02-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0004_pokemonentity_appeared_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemonentity",
            name="attack",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="defense",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="health",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="stamina",
            field=models.IntegerField(default=0),
        ),
    ]
