# Generated by Django 5.2.9 on 2026-02-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pokemon_entities",
            "0005_pokemonentity_attack_pokemonentity_defense_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
