# Generated by Django 5.2.9 on 2026-02-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0006_pokemon_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Name is English"
            ),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="title_jp",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Name is Japanese"
            ),
        ),
    ]
