# Generated by Django 5.2.9 on 2026-02-05 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0007_pokemon_title_en_pokemon_title_jp"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="previous_evolution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_evolutions",
                to="pokemon_entities.pokemon",
            ),
        ),
    ]
