# Generated by Django 5.2.9 on 2026-02-05 20:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0008_pokemon_previous_evolution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="pokemon_images/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="previous_evolution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_evolutions",
                to="pokemon_entities.pokemon",
                verbose_name="Из кого эволюционировал",
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title_en",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Название (английский)",
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title_jp",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Название (японский)",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Время появления"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="attack",
            field=models.IntegerField(default=0, verbose_name="Атака"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="defense",
            field=models.IntegerField(default=0, verbose_name="Защита"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Время исчезновения"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="health",
            field=models.IntegerField(default=0, verbose_name="Здоровье"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="lat",
            field=models.FloatField(verbose_name="Широта"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="level",
            field=models.IntegerField(default=0, verbose_name="Уровень"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="lon",
            field=models.FloatField(verbose_name="Долгота"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="pokemon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to="pokemon_entities.pokemon",
                verbose_name="Покемон",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="stamina",
            field=models.IntegerField(default=0, verbose_name="Выносливость"),
        ),
    ]
