# Generated by Django 5.2.9 on 2026-02-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pokemon_entities",
            "0009_alter_pokemon_description_alter_pokemon_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonentity",
            name="attack",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Атака"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="defense",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Защита"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="health",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Здоровье"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="level",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Уровень"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="stamina",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Выносливость"
            ),
        ),
    ]
